model:
  base_learning_rate: 5.0e-05
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: "image"
    cond_stage_key: "txt"
    image_size: 32
    channels: 4
    cond_stage_trainable: false   # Note: different from the one we trained before
    conditioning_key: crossattn
    scale_factor: 0.18215

    
    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [ 1] # NOTE for resuming. use 10000 if starting from scratch
        cycle_lengths: [ 10000000000000 ] # incredibly large number to prevent corner cases
        f_start: [ 1.e-6 ]
        f_max: [ 1. ]
        f_min: [ 1. ]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 224 #320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        #ckpt_path: models/first_stage_models/kl-f8/model.ckpt
        ckpt_path: models/first_stage_models/kl-f8-deepfashion/deepfashion_v1.ckpt
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder

    extra_cond_stages:
      pose_cond:
        cond_stage_key: "pose"    
        target: ldm.modules.poses.poses.LinearProject
        params:
          input_dim: 75
          output_dim: 768
      face_cond:
        cond_stage_key: "face_embed"    
        target: ldm.modules.poses.poses.LinearProject
        params:
          input_dim: 128
          output_dim: 768

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 16
    num_workers: 16
    #num_val_workers: 0 # Avoid a weird val dataloader issue
    train:
      target: ldm.data.deepfashion.DeepFashionKeypointFaceEmbed
      params:
        pickle_file: data/deepfashion/deepfashion_1.pickle
        folder: /home/soon/datasets/deepfashion/img_256
        is_train: True
        test_size: 64

    validation:
      target: ldm.data.deepfashion.DeepFashionKeypointFaceEmbed
      params:
        pickle_file: data/deepfashion/deepfashion_1.pickle
        folder: /home/soon/datasets/deepfashion/img_256
        is_train: False
        test_size: 64

lightning:
  find_unused_parameters: False

  modelcheckpoint:
    params:
      #every_n_train_steps: 1000
      save_last: true
      every_n_epochs: 1
      save_top_k: 1
      monitor: val/loss

  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 2000
        max_images: 8
        increase_log_steps: False
        log_first_step: True
        #log_all_val: False #True
        log_cond_keys: 
          - pose_image
          - face_image
        log_images_kwargs:
          use_ema_scope: True
          inpaint: False
          plot_progressive_rows: False
          plot_diffusion_rows: False
          N: 8
          unconditional_guidance_scale: 3.0
          unconditional_guidance_label: [""]
    early_stopping:
      target: pytorch_lightning.callbacks.early_stopping.EarlyStopping
      params:
        monitor: val/loss
        mode: min
        patience: 3

  trainer:
    benchmark: True
    num_sanity_val_steps: 1
    accumulate_grad_batches: 1
    #max_epochs: 100
    #max_steps: 40000
