model:
  base_learning_rate: 2.5e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0001
    linear_end: 0.02
    num_timesteps_cond: 1
    log_every_t: 1000
    timesteps: 1000
    use_ema: false
    first_stage_key: image
    cond_stage_key: txt
    concat_key: lr
    image_size:
    - 128
    - 96
    crop_size:
    - 512
    - 352
    channels: 3
    cond_stage_trainable: false
    conditioning_key: hybrid
    scale_factor: 0.18215
    scheduler_config:
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps:
        - 1
        cycle_lengths:
        - 10000000000000
        f_start:
        - 1.0e-06
        f_max:
        - 1.0
        f_min:
        - 1.0
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 6
        out_channels: 3
        model_channels: 256
        attention_resolutions:
        - 2
        - 4
        - 8
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 2
        - 4
        num_heads: 8
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: true
        legacy: false
    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        ckpt_path: models/first_stage_models/kl-f4/model.ckpt
        embed_dim: 3
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder
    extra_cond_stages:
      style_cond:
        target: ldm.modules.encoders.modules.FrozenClipImageEmbedder2
        cond_stage_key: styles
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 4
    train:
      target: ldm.data.deepfashion_inshop.DeepFashionSuperRes
      params:
        folder: /home/soon/datasets/deepfashion_inshop
        image_dir: img_512
        data_file: data/deepfashion/deepfashion_map.csv
        pair_file:
        - data/deepfashion/solo-train-all.csv
        input_mask_type: mask
        image_size:
        - 512
        - 384
        f: 4
        dropout: 0.1
        loss_weight:
          face: 2.5
    validation:
      target: ldm.data.deepfashion_inshop.DeepFashionSuperRes
      params:
        folder: /home/soon/datasets/deepfashion_inshop
        image_dir: img_512
        data_file: data/deepfashion/deepfashion_map.csv
        pair_file:
        - data/deepfashion/solo-test-all.csv
        input_mask_type: mask
        image_size:
        - 512
        - 384
        f: 4
        loss_weight:
          face: 2.5
