model:
  base_learning_rate: 4.5e-6
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    ckpt_path: models/first_stage_models/kl-f8-deepfashion/deepfashion_inshop_256.ckpt  
    monitor: "val/rec_loss"
    embed_dim: 4
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 50001
        kl_weight: 0.000001
        disc_weight: 0.5

    ddconfig:
      double_z: True
      z_channels: 4
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,2,4,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [ ]
      dropout: 0.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 2
    #num_val_workers: 0 # Avoid a weird val dataloader issue
    train:
      target: ldm.data.deepfashion_inshop.DeepFashionPair
      params:
        folder: "/home/soon/datasets/deepfashion_inshop"
        pair_file: 
         #- pairs-train-all.csv
         - solo-train-all.csv
         - solo-test-all.csv
        input_mask_type: smpl
        image_size:
        - 512
        - 384
        f: 8
        image_dir: img_512
        data_file: deepfashion_map.csv
        #df_filter: segm

    validation:
      target: ldm.data.deepfashion_inshop.DeepFashionPair
      params:
        folder: "/home/soon/datasets/deepfashion_inshop"
        pair_file: 
          #- pairs-test-all.csv
          - solo-test-all.csv
        input_mask_type: smpl
        image_size:
        - 512
        - 384
        f: 8
        image_dir: img_512
        data_file: deepfashion_map.csv
        #df_filter: segm

lightning:
  modelcheckpoint:
    params:
      #every_n_train_steps: 5000
      save_last: true
      every_n_epochs: 1
      save_top_k: 1
      monitor: val/rec_loss

    early_stopping:
      target: pytorch_lightning.callbacks.early_stopping.EarlyStopping
      params:
        monitor: val/rec_loss
        mode: min
        patience: 5

  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 4
        increase_log_steps: False
        log_first_step: True
        log_images_kwargs:
          use_ema_scope: True
          inpaint: False
          plot_progressive_rows: False
          plot_diffusion_rows: False
          N: 4
          unconditional_guidance_scale: 3.0
          unconditional_guidance_label: [""]

  trainer:
    benchmark: True
    num_sanity_val_steps: 1
    accumulate_grad_batches: 2
